### ISSUE TITLE
Review Workshop Jupyter Notebook notations 

### ISSUE THREAD

**Issue by tomassosorio** [tomassosorio/DeepLearning#30]
@miguelriemoliveira 

https://github.com/tomassosorio/DeepLearning/tree/workshop/workshop

Analise and review:
  - gen_numpy.ipynb
  - handle_data.ipynb

**Comment by miguelriemoliveira** [comment]
Thanks @tomassosorio . I should review it tonight and ge back to you.

**Comment by miguelriemoliveira** [comment]
Hi @tomassosorio the link to the dataset (I think it is) as expired

> Handle Data
> data link: https://storage.googleapis.com/kaggle-competitions-data/kaggle/3362/train.zip?GoogleAccessId=competitions-data@kaggle-161607.iam.gserviceaccount.com&Expires=1509624943&Signature=Zw9drxGMbINRsrCAm5wsBZWvUu9VDXw%2FmJRK1u%2ByiUwtwVOC4eLgbvMy61OUjd6PRLtL%2Fb9NP0XVEj0MjgNmaD1Oan0RtAAqBgjM17I6hz3wTZPpkVkd3NTzGgggXUx3iGbB4IvCmzy0AJcxl7ojHsXqSEXkxl9l0OTNyf8Cd5QG3h4nIvOv0peuf9aBhjgEYi4CyfCk4WAGU1CSQVjCZdm42oSQBbEYvP9cqJm86gbBZMmrn%2BItwWKRQURDWUI8I%2FDFvSvy8kVtSpuM797hrOLb2i3ffwoldJWhzRtT5o336FwU22bptlqTkXj%2FHMlMOMQCtBGpW1rQ1FkCR2qCrA%3D%3D
> 

Can you reenable?

**Comment by miguelriemoliveira** [comment]
Hi @tomassosorio 

I started revising the handle data but its taking long (see ee849bbb8eb9edb8776d39aef86f75d5da0f20ec).

I think we should be more explicit about what people have to write (that is not written yet).

You have this in comments but they often are not highlighted enough. I tried to do this by stating the objective of each code section (what must be done, what is the methodology).

Right now I will be out of time so can you please try to see how you can use the idea to improve and I will try to look into it again later.

**Comment by tomassosorio** [comment]
Hi @miguelriemoliveira 
Thank you for your time.

I will try to improve that aspect that you referred as soon as possible.

**Comment by miguelriemoliveira** [comment]
Hi @tomassosorio 

unfortunately I had no more time during the weekend. Today I will have classes until 20h so I am afraid I will not be of much help (I could try to revise a bit tonight but it will be too late anyway for you to change stuff).

In any case I think this workshop is already very well prepared so tomorrow it will go fine.

If you really need some help mail me and tonight at 22h30 I will try to check it.

**Comment by miguelriemoliveira** [comment]
if I am off the hook and you don't need me to revise more please close the issue :)

**Comment by tomassosorio** [comment]
https://github.com/tomassosorio/DeepLearning/blob/workshop/workshop/handle_data.ipynb

Update and revised.
