### ISSUE TITLE
Cannot install opencv 2.4.9.1 for workshop

### ISSUE THREAD

**Issue by miguelriemoliveira** [tomassosorio/DeepLearning#32]
Hi @tomassosorio 

you specify opencv's version but my pip complains

> (deeplearning) mike@X360:~$ sudo pip install tensorflow keras tqdm opencv-python==2.4.9.1 jupyter
> The directory '/home/mike/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/home/mike/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting tensorflow
>   Downloading tensorflow-1.4.0-cp27-cp27mu-manylinux1_x86_64.whl (40.7MB)
>     100% |████████████████████████████████| 40.8MB 46kB/s 
> Collecting keras
>   Downloading Keras-2.0.9-py2.py3-none-any.whl (299kB)
>     100% |████████████████████████████████| 307kB 1.2MB/s 
> Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages
> Collecting opencv-python==2.4.9.1
>   Could not find a version that satisfies the requirement opencv-python==2.4.9.1 (from versions: 3.1.0.0, 3.1.0.1, 3.1.0.2, 3.1.0.3, 3.1.0.4, 3.1.0.5, 3.2.0.6, 3.2.0.7, 3.2.0.8, 3.3.0.9, 3.3.0.10)
> No matching distribution found for opencv-python==2.4.9.1
> 

can I just install some other version?

**Comment by tomassosorio** [comment]
I just installed the last version opencv-python (3.3.0.10) and is working. I will update the README.md file.
Thank you for the notice.

**Comment by tomassosorio** [comment]
Updated: https://github.com/tomassosorio/DeepLearning/blob/workshop/README.md
