### ISSUE TITLE
Replace absolute paths with relative paths

### ISSUE THREAD

**Issue by davidtvs** [tomassosorio/DeepLearning#35]
File manipulation should use relative paths instead of absolute paths.

Example:
```python
data_dir = '/home/tomas/Documents/Pessoal/Workshop/data'
```
should be repalced by
```python
base_dir = os.path.dirname(__file__)
data_folder = 'data`
org_path = os.path.join(base_dir, org_folder)
```

**Comment by tomassosorio** [comment]
Hi,
you are absolutely right but for simplicity porpuses, I decided to use the least number of methods possible that are out of the scope of the workshop, for this reason, I opted for each person just chose the localization that they pretend to put their data.
