### ISSUE TITLE
Test Raccon object detection

### ISSUE THREAD

**Issue by miguelriemoliveira** [tomassosorio/DeepLearning#9]
Could be a good second step since it has training.

https://medium.com/towards-data-science/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9

**Comment by tomassosorio** [comment]
LossTensor is inf or nan. : Tensor had NaN values

After successfully creating the TFRecord file, when trying to run it to train, it appears the error above.

**Comment by miguelriemoliveira** [comment]
For now we will close this issue and work on PyTorch.

If necessary will reopen issue.
